### ISSUE TITLE
Typo3 11 version release

### ISSUE THREAD

**Issue by abvdveen** [liquidlight/typo3-cc-routing#1]
I notice in the repo Typo3 11 compat changes have been added. When will these be available in a TER release? Using composer on 11 I now get an error on the last release: 'liquidlight/cc-routing 1.2.3 requires typo3/cms-core ^9.5 || ^10.4'.

**Comment by mikestreety** [comment]
Hi @abvdveen I'll release it today - I put it on there for testing and completely forgot I hadn't released it!

Thanks for the nudge :)

**Comment by abvdveen** [comment]
Thanks for the fast response!

**Comment by mikestreety** [comment]
@abvdveen 

All released - 1.3.1 is the latest:

- TER: https://extensions.typo3.org/extension/cc_routing
- Packagist: https://packagist.org/packages/liquidlight/cc-routing

Let me know if you have any issues
