### ISSUE TITLE
TCA Migrations

### ISSUE THREAD

**Issue by abvdveen** [liquidlight/typo3-cc-routing#2]
Running 'Check TCA Migrations' under 'Upgrade' gives:

The 'tx_ccrouting_pathsegment' TCA configuration 'showRecordFieldList' inside the section 'interface' is not evaluated anymore and should therefore be removed.

**Comment by mikestreety** [comment]
Thanks @abvdveen - i'll take a look :)

**Comment by mikestreety** [comment]
I think this is fixed now :)
