### ISSUE TITLE
Typo3 12.4 compatibility

### ISSUE THREAD

**Issue by abvdveen** [liquidlight/typo3-cc-routing#3]
Will there be a version for Typo3 12.4?

**Comment by mikestreety** [comment]
Hi @abvdveen, there is no immediate plan as we are pretty snowed under at the moment but would welcome a PR if you (or anyone) has the time!

**Comment by abvdveen** [comment]
Hi @mikestreety, thanks for letting me know. I will check whether we need the functionality of your ext in 12, or that it perhaps is integrated in the core. If we still need it and the latter is not the case, I'll try to make your ext compatible and let you know if that's succesfull.

**Comment by mikestreety** [comment]
I'll be interesting in your findings either way!
